name:                redis-job
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/kayhide/redis-job
license:             BSD3
author:              Hideaki KAWAI
maintainer:          kayhide@gmail.com
copyright:           kayhide
category:            Web
extra-source-files:
  - README.md

dependencies:
  - async
  - base
  - bytestring
  - classy-prelude
  - containers
  - deepseq
  - directory
  - exceptions
  - filepath
  - mtl
  - primitive
  - stm
  - text
  - time
  - transformers
  - typed-process
  - unliftio
  - unliftio-core
  - unordered-containers
  - vector
  - hedis
  - aeson
  - lens
  - persistent
  - persistent-template
  - persistent-postgresql
  - resource-pool
  - monad-logger
  - extensible

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

executables:
  redis-job:
    source-dirs:      src
    main:             Main.hs
